# This file is automatically generated, do not edit directly.

class Griffin < Formula
  desc "CLI tool for pulling secrets and other config, with version control."
  homepage "https://github.com/griffin-cli/griffin-cli"
  version_scheme 1

  version "v0.5.2"

  url "https://github.com/griffin-cli/griffin-cli/releases/download/v0.5.2/griffin-v0.5.2-darwin-x64.tar.xz"
  sha256 "82c9e0dc90eb9a5c904127f597341a46b31e1ef879b990727dbccb0065fad945"

  on_macos do
    on_arm do
      url "https://github.com/griffin-cli/griffin-cli/releases/download/v0.5.2/griffin-v0.5.2-darwin-arm64.tar.xz"
      sha256 "66ee51c61cdb8715eab7d3ec094af207481db58de57f626819e9e4cd5a0841f1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/griffin-cli/griffin-cli/releases/download/v0.5.2/griffin-v0.5.2-linux-x64.tar.xz"
      sha256 "be626c775890df5f95e49fba810a5e56088c0049380295b3340c4868b1573129"
    end
    on_arm do
      url "https://github.com/griffin-cli/griffin-cli/releases/download/v0.5.2/griffin-v0.5.2-linux-arm64.tar.xz"
      sha256 "5ebe55a4596c176308b7704adafaad11d48973bd4ea932b0a8a58ca4e8b0fe41"
    end
  end

  def install
    inreplace "bin/griffin", /^CLIENT_HOME=/, "export GRIFFIN_OCLIF_CLIENT_HOME=#{libexec/"dist"}\nCLIENT_HOME="
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/griffin"
  end

  def caveats; <<~EOS
    Enable autocomplete for zsh by running

      $ griffin autocomplete zsh

    If you're using bash, run

      $ griffin autocomplete bash
  EOS
  end

  test do
    system bin/"griffin", "version"
  end
end
