# This file is automatically generated, do not edit directly.

class Griffin < Formula
  desc "CLI tool for pulling secrets and other config, with version control."
  homepage "https://github.com/griffin-cli/griffin-cli"
  version_scheme 1

  version "v0.5.0"

  url "https://github.com/griffin-cli/griffin-cli/releases/download/v0.5.0/griffin-v0.5.0-darwin-x64.tar.xz"
  sha256 "6a6d2b4d9a90b3205dbd4702709fea30721aee2850b6445ea89f3b4ae76dddd9"

  on_macos do
    on_arm do
      url "https://github.com/griffin-cli/griffin-cli/releases/download/v0.5.0/griffin-v0.5.0-darwin-arm64.tar.xz"
      sha256 "2635cb1f6f223ff58476dfc34ee53cac99ca62e6b7e5490e824fd48af16fa8cc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/griffin-cli/griffin-cli/releases/download/v0.5.0/griffin-v0.5.0-linux-x64.tar.xz"
      sha256 "9b31615d3f3baa09b153647beb7e1ad2d825e2a822273aac912fd0ee085877e8"
    end
    on_arm do
      url "https://github.com/griffin-cli/griffin-cli/releases/download/v0.5.0/griffin-v0.5.0-linux-arm64.tar.xz"
      sha256 "d1a4f8d6d06cf59c2227044fb320e3ca881af50e73636e030252be6215a67e22"
    end
  end

  def install
    inreplace "bin/griffin", /^CLIENT_HOME=/, "export GRIFFIN_OCLIF_CLIENT_HOME=#{libexec/"dist"}\nCLIENT_HOME="
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/griffin"
  end

  def caveats; <<~EOS
    Enable autocomplete for zsh by running

      $ griffin autocomplete zsh

    If you're using bash, run

      $ griffin autocomplete bash
  EOS
  end

  test do
    system bin/"griffin", "version"
  end
end
