# This file is automatically generated, do not edit directly.

class Griffin < Formula
  desc "CLI tool for pulling secrets and other config, with version control."
  homepage "https://github.com/griffin-cli/griffin-cli"
  version_scheme 1

  version "v0.3.0"

  url "https://github.com/griffin-cli/griffin-cli/releases/download/v0.3.0/griffin-v0.3.0-darwin-x64.tar.xz"
  sha256 "bebd032fa2d95808711c4421656eea4964f6ab839b2004f0b745443b57aa0fad"

  on_macos do
    on_arm do
      url "https://github.com/griffin-cli/griffin-cli/releases/download/v0.3.0/griffin-v0.3.0-darwin-arm64.tar.xz"
      sha256 "e256a30e1cdec9636123ad6dca1e9e089c54bd9a243383fb3ab9e288890e490c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/griffin-cli/griffin-cli/releases/download/v0.3.0/griffin-v0.3.0-linux-x64.tar.xz"
      sha256 "75e2bd6d45f0b68d892ba4f850e3b5e947161580d5f7651fbc560ab91281d8b9"
    end
    on_arm do
      url "https://github.com/griffin-cli/griffin-cli/releases/download/v0.3.0/griffin-v0.3.0-linux-arm64.tar.xz"
      sha256 "1ab1d04f3bdc3603e58ece7aa792c7dd283cd79cdb51773b897f54817627eed8"
    end
  end

  def install
    inreplace "bin/griffin", /^CLIENT_HOME=/, "export GRIFFIN_OCLIF_CLIENT_HOME=#{libexec/"dist"}\nCLIENT_HOME="
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/griffin"
  end

  def caveats; <<~EOS
    Enable autocomplete for zsh by running

      $ griffin autocomplete zsh

    If you're using bash, run

      $ griffin autocomplete bash
  EOS
  end

  test do
    system bin/"griffin", "version"
  end
end
