name: Update Formula

on:
  workflow_dispatch:
    inputs:
      # Required
      version:
        required: true
        type: string

      sha256_mac_intel:
        required: true
        type: string

      sha256_mac_arm:
        required: true
        type: string

      sha256_linux_intel:
        required: true
        type: string

      sha256_linux_arm:
        required: true
        type: string

      # Optional
      base_url:
        required: false
        type: string
        default: https://github.com/griffin-cli/griffin-cli/releases/download

      skip_push:
        required: false
        type: boolean
        default: false


jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Formula
        run: |
          rm -f Formula/griffin.rb || true

          BASE_URL=${{ inputs.base_url }}/${{ inputs.version }}/griffin-${{ inputs.version }}
          EXT=tar.xz

          export GRIFFIN_VERSION=${{ inputs.version }}

          export DOWNLOAD_URL_MAC_INTEL=$BASE_URL-darwin-x64.$EXT
          export SHA256_MAC_INTEL=${{ inputs.sha256_mac_intel }}

          export DOWNLOAD_URL_MAC_ARM=$BASE_URL-darwin-arm64.$EXT
          export SHA256_MAC_ARM=${{ inputs.sha256_mac_arm }}

          export DOWNLOAD_URL_LINUX_INTEL=$BASE_URL-linux-x64.$EXT
          export SHA256_LINUX_INTEL=${{ inputs.sha256_linux_intel }}

          export DOWNLOAD_URL_LINUX_ARM=$BASE_URL-linux-arm64.$EXT
          export SHA256_LINUX_ARM=${{ inputs.sha256_linux_arm }}

          envsubst < ./templates/griffin.rb > ./Formula/griffin.rb

      - name: Push Changes
        run: |
          git add Formula
          git diff
          git commit -m "griffin ${{ inputs.version }}"

          ${{ inputs.skip_push && '' || 'git push origin main' }}
